// day-3/react-app/src/components/Form.jsx
import React, { useState } from 'react';
import SelectOptions from './SelectOptions';

function Form({ categories, addMovie }) {
  const [formData, setFormData] = useState({
    title: '',
    image: '',
    categoryIds: [],
  });

  function handleSubmit(event) {
    event.preventDefault();
    addMovie({
      ...formData,
      categories: formData.categoryIds,
    });
  }

  function handleInputChange(key) {
    return function (event) {
      setFormData({
        ...formData,
        [key]: event.target.value,
      });
    };
  }

  function handleSelectChange(event) {
    const categoryIds = [...event.target.selectedOptions].map(
      (categoryId) => categoryId.value
    );

    setFormData({
      ...formData,
      categoryIds,
    });
  }

  return (
    <form className="movie_form" onSubmit={handleSubmit}>
      <div className="form-group">
        <label htmlFor="title">Título</label>
        <input
          type="text"
          className="form-control"
          name="title"
          id="title"
          value={formData.title}
          onChange={handleInputChange('title')}
        />
      </div>
      <div className="form-group">
        <label htmlFor="image">Link da imagem</label>
        <input
          type="url"
          className="form-control"
          name="image"
          id="image"
          value={formData.image}
          onChange={handleInputChange('image')}
        />
      </div>
      <div className="form-group">
        <label htmlFor="categories">Categoria</label>
        <select
          name="categories"
          className="form-control"
          id="categories"
          value={formData.categoryIds}
          onChange={handleSelectChange}
          multiple
        >
          <SelectOptions categories={categories} />
        </select>
      </div>

      <button type="submit" className="btn btn-primary">
        Cadastrar
      </button>
    </form>
  );
}

export default Form;

// day-3/vue-app/src/components/Form.vue
<template>
  <form id="movie_form" v-on:submit.prevent="addMovie">
    <div class="form-group">
      <label for="title">Título</label>
      <input type="text" v-model="title" name="title" class="form-control" id="title" />
    </div>

    <div class="form-group">
      <label for="image">Link da imagem</label>
      <input type="url" v-model="image" name="image" class="form-control" id="image" />
    </div>

    <div class="form-group">
      <label for="categoria">Categoria</label>
      <select v-model="categoryIds" name="categories" class="form-control" multiple>
        <option
          v-for="category in categories"
          :value="category.id"
          :key="category.id"
        >{{category.title}}</option>
      </select>
    </div>

    <button type="submit" class="btn btn-primary">Cadastrar</button>
  </form>
</template>

<script>
export default {
  name: 'Form',
  props: {
    categories: {
      type: Array,
      required: true,
    },
  },
  data() {
    return {
      title: '',
      image: '',
      categoryIds: [],
    };
  },
  methods: {
    addMovie() {
      console.log(this.title, this.image, this.categoryIds);
      this.$emit('add-movie', {
        title: this.title,
        image: this.image,
        categories: this.categoryIds,
      });
    },
  },
};
</script>
