// day-3/vue-app/src/components/Card.vue
<template>
  <div class="card">
    <img class="card-img-top" :src="image" :alt="title" />
    <div class="card-body">
      <h3 class="card-title">{{title}}</h3>
      <p class="card-text">
        <a
          v-for="category in categories"
          href="#"
          class="badge badge-secondary mr-1"
          :key="category.id"
        >
        {{ category }}
        </a>
      </p>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Card',
  props: {
    categories: {
      type: Array,
      required: true
    },
    title: {
      type: String,
      required: true
    },
    image: {
      type: String,
      required: true
    }
  }
};
</script>

// day-3/react-app/src/components/Card.jsx
import React from 'react';

import getCategoryById from '../utils/getCategoryById';

function Card({ title, image, categoryIds }) {
  return (
    <div className="card">
      <img src={image} alt={title} className="card-img-top" />
      <div className="card-body">
        <h3 className="card-title">{title}</h3>
        <p className="card-text">
          {categoryIds.map((categoryId, categoryIndex) => (
            <span className="badge badge-secondary mr-1" key={categoryIndex}>
              {getCategoryById(categoryId).title}
            </span>
          ))}
        </p>
      </div>
    </div>
  );
}

export default Card;
